apiVersion: app.slooper.io/v1 
Kind: Configurator
metadata:
  name: sloop-config
spec:
  template: default
  global:
    namespace: app2
    values:
      - values.yaml
  sources:
    - name: app
      path: app/*.yaml
      namespace: app-ns
      values:
        - values.yaml 
    - name: app2
      path: app2/*.yaml
      namespace: app2-ns
      values:
        - values.yaml

    