replicaCount: 1

name: example-1

image:
  repository: nginx
  tag: 1.14.2
  pullPolicy: IfNotPresent

labels:
  app.kubernetes.io/name: example-1

selectors:
  app.kubernetes.io/name: example-1
  app.kubernetes.io/package: sloop-package-dev

service:
  type: ClusterIP
  port: 80
  protocol: TCP

volumes:
  namesper:
    daily: true


